### PR TITLE
grub cfg: don't explicitly set root prefix

### PR DESCRIPTION
**Pull request by jiazhang0**
The root prefix would be automatically probed if not explicitly
specified and the probed value would point to the device where the boot
device selected by BIOS boot manager locates. Usually, this is the expected
result without the necessity of explicitly setting it, unless an
exception occurs.

Hence, the usual behavior should determine the setting of the templates so
explicitly setting root prefix is not required in the templates. Otherwise,
it would easily break the typical hardware setup, such as a USB thumb drive
for the installer and a hard disk drive for the runtime, if hd0 doesn't
point to the expected device.

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>

### CODE REVIEW

**Comment by zeddii** [comment]
This isn't working in my configuration.

What you aren't describing is *how* you end up in a situation where this grub.cfg is being used and the boot device is not hd0,1

We do not want to depend on probing, or the BIOS. We need to be explicit in our device mappings.

If this does need to vary, make the value in the file something that the installer/image generation phase can modify, since that means we are explicitly mapping it to our known config without counting on a probe function in the BIOS.

**Comment by jiazhang0** [comment]
hd0,1 is the first disk device returned by BIOS. BIOS boot manager takes the responsibility of emulating all supported disk devices but it doesn't mange to sort these device in order as expected. In other wise, the order in the device list created by BIOS internally is unpredictable, and this order is never relevant with the boot device order you set in BIOS setup.

When booting a device, it is predictable that the root and prefix variable is set to "current" device if not explicitly specified. If we specify them with hd0,1, but we cannot make sure the boot device is the first device returned by BIOS, the problem will happen. The result may be boot failure or boot to another system.

If creating a mapping file for grub in installer is necessary, at least we should remove hd0,1 for the grub-usb.cfg files used by the installer image, allowing depending on the auto probing.

**Comment by masselstine** [comment]
@jiazhang0 let's say there is one sd device and one mmc and we have grub installed on the mmc. We use the BIOS to set the mmc device as the boot device. You are implying that (hd0,1) can be the sd device or the mmc device, depending on how the BIOS probing results? But if we don't set root= it will always be the same device from which grub is installed?

**Comment by jiazhang0** [comment]
Yes hd0 cannot be predicted unless we use grub device map, but this doesn't always work for the live image. For installer image, we have the opportunity to create such a mapping but we don't do it yet.

Back to the probing order. Even you always get an expected result in a certain machine but that is not meaning it is always correct on other machines. More specifically, the boot order set in BIOS is decided by a EFI variable called BootOrder. grub doesn't use this variable to create the hd device list.

If we don't set root=, we always boot the system from the same device where grub is installed. This is the most common situation and our installer also follows this logic to set up the fat partition for EFI boot.

In my KVM smoking testing environment, I assign a USB thumb drive to KVM and the boot always fails when searching the bzImage even I set the usb device as the first boot device in BootOrder. There are several virtual disks provided by OVMF firmware by default and you can observe them in EFI shell. So here another order is listed by EFI shell, but trust me this order is also not the probing device list grub really retrieves. The real order is determined by how BIOS probes the disk device and this order is internal.

**Comment by jiazhang0** [comment]
Here is the background info.

- grub core (grub${EFI_ARCH}.efi) initialization flow
  * Initialize EFI subsystem
  * Print banner: "Welcome to GRUB!\n\n"
  * Load pre-loaded grub modules
  * Set the root device and initialize prefix/root variable
    > Attempt to parse prefix module
    > Otherwise automatically probe BIOS and initialize prefix/root
      variable to the value where grub core image is launched. More
      specifically, each block device returned from BIOS are added
      to an internal device list managed by grub core, and then grub
      finds out the device which matches up where grub core is installed.
     The index of found device in the device list is the order number of
     grub hard disk (hdX).
  * Export root and prefix variables
  * Register core commands: set, unset, ls, insmod
  * Load and parse the config module
    > This may overwrite the setting of root and prefix variables
  * Load the normal mode module and execute the normal mode if possible
  * Fallback to rescue mode with the prompt: "Entering rescue mode...\n" if exiting
    from the normal mode.

- prefix module
  Built into grub core image. The format of content:
  ($device）$path
   where $device is formatted with x,y or x. $path is optional.

- config module
  Built into grub core image.
  Support to run the commands granted in the rescure mode.
  A *BAD* example in oe-core:
  search.file ($cmdpath)/EFI/BOOT/grub.cfg root
  set prefix=($root)/EFI/BOOT

- grub module
  Relocatable ELF object (.mod)

- Pulsar
  No config and prefix modules.

**Comment by masselstine** [comment]
Based on this I think we can take the change but we should think about providing an example/details on how to create a device map. Sure it can't be generic but we also don't want to leave our customers wondering how to work around this limitation.

**Comment by jiazhang0** [comment]
@masselstine the device map seems to be available for legacy boot. EFI boot doesn't have such a mapping mechanism.

**Pull request closed without merging**
